services:
  java:
    build: .
    # command: ["mvn", "exec:java"]
    command: tail -f /dev/null
    volumes:
      - .:/app
    container_name: java_app
    working_dir: /app
    mem_limit: 512m
    tty: true 
